//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int picture_id { get; set; }
        public int tagger_id { get; set; }
        public int tagged_id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public bool seen { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
    }
}
